#!/bin/sh
# Real ESP32 compile of the three sketches (needs arduino-cli with the esp32
# core and the TinyGSM + ESP_SSLClient libraries installed). Prototypes are
# generated by arduino_preprocess.py the way the Arduino IDE places them, so
# "'X' does not name a type" errors show up here as they do in the IDE.
#   ./compile_real.sh            (set ARDUINO_CLI=/path/to/arduino-cli if not on PATH)
cd "$(dirname "$0")" || exit 1
CLI="${ARDUINO_CLI:-arduino-cli}"
status=0
for s in gprs_forwarder bale_direct sms_forwarder sim800_test; do
  d="build/real/$s"
  rm -rf "$d" && mkdir -p "$d"
  printf '// code is in sketch.cpp\n' > "$d/$s.ino"
  python3 arduino_preprocess.py "../$s/$s.ino" "$d/sketch.cpp" >/dev/null
  echo "=== $s"
  "$CLI" compile -b esp32:esp32:esp32 "$d" 2>&1 | grep -E "error:|Sketch uses" || status=1
  "$CLI" compile -b esp32:esp32:esp32 "$d" >/dev/null 2>&1 || status=1
done
exit $status
